objectName
isAvatar
isPlayingAvatarSound
isListeningToAudioStream
lastReceivedAudioLoudness
sessionUUID

destroyed(QObject*)
destroyed()
objectNameChanged(QString)
finished()
run()
stop()
sendStatsPacket()
clearQueuedCheckIns()
domainSettingsRequestFailed()
startAvatarAudioTimer()
stopAvatarAudioTimer()
playAvatarSound(SharedSoundPointer)
