AvatarList DATA

destroyed(QObject*)
destroyed()
objectNameChanged(QString)
avatarAddedEvent(QUuid)
avatarRemovedEvent(QUuid)
avatarSessionChangedEvent(QUuid,QUuid)
isAvatarInRange(glm::vec3,float)
getAvatarIdentifiers()
getAvatar(QUuid)
setShouldShowReceiveStats(bool)
updateAvatarRenderStatus(bool)
setLocalLights(QVector<AvatarManager::LocalLight>)
getLocalLights()
getAvatarDataRate(QUuid,QString)
getAvatarDataRate(QUuid)
findRayIntersection(PickRay,QScriptValue,QScriptValue)
findRayIntersection(PickRay,QScriptValue)
findRayIntersection(PickRay)
