AvatarList.getAvatar result Data

objectName
position
scale
handPosition
bodyYaw
bodyPitch
bodyRoll
orientation
headOrientation
headPitch
headYaw
headRoll
velocity
angularVelocity
audioLoudness
audioAverageLoudness
displayName
sessionDisplayName
skeletonModelURL
attachmentData
jointNames
sessionUUID
sensorToWorldMatrix
controllerLeftHandMatrix
controllerRightHandMatrix
skeletonOffset

destroyed(QObject*)
destroyed()
objectNameChanged(QString)
sendAvatarDataPacket()
sendIdentityPacket()
setJointMappingsFromNetworkReply()
setSessionUUID(QUuid)
getAbsoluteJointRotationInObjectFrame(int)
getAbsoluteJointTranslationInObjectFrame(int)
setAbsoluteJointRotationInObjectFrame(int,glm::quat)
setAbsoluteJointTranslationInObjectFrame(int,glm::vec3)
getTargetScale()
resetLastSent()
setHandState(char)
getHandState()
setRawJointData(QVector<JointData>)
setJointData(int,glm::quat,glm::vec3)
setJointRotation(int,glm::quat)
setJointTranslation(int,glm::vec3)
clearJointData(int)
isJointDataValid(int)
getJointRotation(int)
getJointTranslation(int)
setJointData(QString,glm::quat,glm::vec3)
setJointRotation(QString,glm::quat)
setJointTranslation(QString,glm::vec3)
clearJointData(QString)
isJointDataValid(QString)
getJointRotation(QString)
getJointTranslation(QString)
getJointRotations()
setJointRotations(QVector<glm::quat>)
setJointTranslations(QVector<glm::vec3>)
clearJointsData()
getJointIndex(QString)
getJointNames()
setBlendshape(QString,float)
getAttachmentsVariant()
setAttachmentsVariant(QVariantList)
updateAvatarEntity(QUuid,QByteArray)
clearAvatarEntity(QUuid)
getAttachmentData()
setAttachmentData(QVector<AttachmentData>)
attach(QString,QString,glm::vec3,glm::quat,float,bool,bool,bool)
attach(QString,QString,glm::vec3,glm::quat,float,bool,bool)
attach(QString,QString,glm::vec3,glm::quat,float,bool)
attach(QString,QString,glm::vec3,glm::quat,float)
attach(QString,QString,glm::vec3,glm::quat)
attach(QString,QString,glm::vec3)
attach(QString,QString)
attach(QString)
detachOne(QString,QString)
detachOne(QString)
detachAll(QString,QString)
detachAll(QString)
getAvatarEntityData()
setAvatarEntityData(AvatarEntityMap)
getSensorToWorldMatrix()
getControllerLeftHandMatrix()
getControllerRightHandMatrix()
getLeftPalmPosition()
getLeftPalmRotation()
getRightPalmPosition()
getRightPalmRotation()
setModelURLFinished(bool)
getDefaultJointRotation(int)
getDefaultJointTranslation(int)
setSkeletonOffset(glm::vec3)
getSkeletonOffset()
getJointPosition(int)
getJointPosition(QString)
getNeckPosition()
getAcceleration()
getParentID()
setParentID(QUuid)
getParentJointIndex()
setParentJointIndex(ushort)